from typing import List, Dict
from datetime import datetime


def score_badge(score: int) -> str:
    if score >= 8:
        return "🟢 Strong"
    elif score >= 6:
        return "🟡 Good"
    elif score >= 4:
        return "🟠 Moderate"
    else:
        return "🔴 Low"


def generate_md_report(leads: List[Dict], search_params: Dict) -> str:
    """Generate a clean, structured markdown prospecting report."""

    now = datetime.now().strftime("%d/%m/%Y at %H:%M")
    total = len(leads)
    strong = sum(1 for l in leads if l.get("fit_score", 0) >= 7)

    lines = [
        "# MaIA — LinkedIn Prospecting Report",
        f"> Generated by MaIA · Agencia Kairos AI Agent · {now}",
        "",
        "---",
        "",
        "## Search Parameters",
        "",
        f"| Parameter | Value |",
        f"|---|---|",
        f"| Industry | {search_params.get('industry') or '—'} |",
        f"| Role / Title | {search_params.get('role') or '—'} |",
        f"| Location | {search_params.get('location') or '—'} |",
        f"| Company Size | {search_params.get('company_size') or '—'} |",
        f"| Keywords | {search_params.get('keywords') or '—'} |",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"- **Total leads found:** {total}",
        f"- **Strong fit (7+):** {strong}",
        f"- **Ready to contact:** {strong}",
        "",
        "---",
        "",
        "## Leads",
        ""
    ]

    for i, lead in enumerate(leads, 1):
        score = lead.get("fit_score", 0)
        badge = score_badge(score)
        name = lead.get("name") or "Unknown"
        role = lead.get("role") or "—"
        company = lead.get("company") or "—"
        service = lead.get("recommended_service") or "—"
        url = lead.get("linkedin_url") or ""
        why = lead.get("why_this_lead") or "—"
        angle = lead.get("conversation_angle") or "—"

        lines += [
            f"### {i}. {name}",
            "",
            f"| | |",
            f"|---|---|",
            f"| **Role** | {role} |",
            f"| **Company** | {company} |",
            f"| **Fit Score** | {badge} · {score}/10 |",
            f"| **Recommended Service** | {service} |",
            f"| **LinkedIn** | [View Profile]({url}) |",
            "",
            f"**Why this lead**",
            f"> {why}",
            "",
            f"**How to open the message**",
            f"> {angle}",
            "",
            "---",
            ""
        ]

    lines += [
        "",
        "*This report was generated by MaIA, the AI prospecting agent of Agencia Kairos.*",
        "*Review each lead before reaching out. MaIA surfaces signals — you bring the judgment.*"
    ]

    return "\n".join(lines)
