from typing import List, Dict
from datetime import datetime


def score_badge(score: int, language: str = "en") -> str:
    labels = {
        "en": {"strong": "Strong", "good": "Good", "moderate": "Moderate", "low": "Low"},
        "es": {"strong": "Fuerte", "good": "Bueno", "moderate": "Medio", "low": "Bajo"},
    }
    text = labels.get(language, labels["en"])

    if score >= 8:
        return f"🟢 {text['strong']}"
    elif score >= 6:
        return f"🟡 {text['good']}"
    elif score >= 4:
        return f"🟠 {text['moderate']}"
    else:
        return f"🔴 {text['low']}"


def generate_md_report(leads: List[Dict], search_params: Dict) -> str:
    """Generate a clean, structured markdown prospecting report."""
    language = "es" if search_params.get("language") == "es" else "en"

    now = datetime.now().strftime("%d/%m/%Y at %H:%M")
    total = len(leads)
    strong = sum(1 for l in leads if l.get("fit_score", 0) >= 7)

    if language == "es":
        labels = {
            "title": "# MaIA — Reporte de Prospección en LinkedIn",
            "generated": "Generado por MaIA · Agente de IA de Agencia Kairos",
            "search_params": "## Parámetros de Búsqueda",
            "param": "Parámetro",
            "value": "Valor",
            "industry": "Industria",
            "role": "Rol / Cargo",
            "location": "Ubicación",
            "company_size": "Tamaño de Empresa",
            "keywords": "Palabras Clave",
            "summary": "## Resumen",
            "total": "Total de leads encontrados",
            "strong": "Ajuste alto (7+)",
            "ready": "Listos para contactar",
            "leads": "## Leads",
            "unknown": "Desconocido",
            "role_label": "Rol",
            "company_label": "Empresa",
            "fit_score": "Puntaje de Ajuste",
            "service": "Servicio Recomendado",
            "linkedin": "LinkedIn",
            "view_profile": "Ver Perfil",
            "why": "Por qué este lead",
            "how": "Cómo abrir el mensaje",
            "footer1": "*Este reporte fue generado por MaIA, el agente de prospección con IA de Agencia Kairos.*",
            "footer2": "*Revisa cada lead antes de contactarlo. MaIA detecta señales, tú aplicas criterio.*",
        }
    else:
        labels = {
            "title": "# MaIA — LinkedIn Prospecting Report",
            "generated": "Generated by MaIA · Agencia Kairos AI Agent",
            "search_params": "## Search Parameters",
            "param": "Parameter",
            "value": "Value",
            "industry": "Industry",
            "role": "Role / Title",
            "location": "Location",
            "company_size": "Company Size",
            "keywords": "Keywords",
            "summary": "## Summary",
            "total": "Total leads found",
            "strong": "Strong fit (7+)",
            "ready": "Ready to contact",
            "leads": "## Leads",
            "unknown": "Unknown",
            "role_label": "Role",
            "company_label": "Company",
            "fit_score": "Fit Score",
            "service": "Recommended Service",
            "linkedin": "LinkedIn",
            "view_profile": "View Profile",
            "why": "Why this lead",
            "how": "How to open the message",
            "footer1": "*This report was generated by MaIA, the AI prospecting agent of Agencia Kairos.*",
            "footer2": "*Review each lead before reaching out. MaIA surfaces signals — you bring the judgment.*",
        }

    lines = [
        labels["title"],
        f"> {labels['generated']} · {now}",
        "",
        "---",
        "",
        labels["search_params"],
        "",
        f"| {labels['param']} | {labels['value']} |",
        f"|---|---|",
        f"| {labels['industry']} | {search_params.get('industry') or '—'} |",
        f"| {labels['role']} | {search_params.get('role') or '—'} |",
        f"| {labels['location']} | {search_params.get('location') or '—'} |",
        f"| {labels['company_size']} | {search_params.get('company_size') or '—'} |",
        f"| {labels['keywords']} | {search_params.get('keywords') or '—'} |",
        "",
        "---",
        "",
        labels["summary"],
        "",
        f"- **{labels['total']}:** {total}",
        f"- **{labels['strong']}:** {strong}",
        f"- **{labels['ready']}:** {strong}",
        "",
        "---",
        "",
        labels["leads"],
        ""
    ]

    for i, lead in enumerate(leads, 1):
        score = lead.get("fit_score", 0)
        badge = score_badge(score, language)
        name = lead.get("name") or labels["unknown"]
        role = lead.get("role") or "—"
        company = lead.get("company") or "—"
        service = lead.get("recommended_service") or "—"
        url = lead.get("linkedin_url") or ""
        why = lead.get("why_this_lead") or "—"
        angle = lead.get("conversation_angle") or "—"

        lines += [
            f"### {i}. {name}",
            "",
            f"| | |",
            f"|---|---|",
            f"| **{labels['role_label']}** | {role} |",
            f"| **{labels['company_label']}** | {company} |",
            f"| **{labels['fit_score']}** | {badge} · {score}/10 |",
            f"| **{labels['service']}** | {service} |",
            f"| **{labels['linkedin']}** | [{labels['view_profile']}]({url}) |",
            "",
            f"**{labels['why']}**",
            f"> {why}",
            "",
            f"**{labels['how']}**",
            f"> {angle}",
            "",
            "---",
            ""
        ]

    lines += [
        "",
        labels["footer1"],
        labels["footer2"]
    ]

    return "\n".join(lines)
